//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camion
    {
        public int Camion_ID { get; set; }
        public int Ejes_ID { get; set; }
        public string Matricula_camion { get; set; }
        public string Matricula_zorra { get; set; }
        public string Marca { get; set; }
        public decimal Tara { get; set; }
        public string Comentarios { get; set; }
    }
}
