//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chofer
    {
        public int Chofer_ID { get; set; }
        public string Nombre_completo { get; set; }
        public string Empresa { get; set; }
        public string Comentarios { get; set; }
        public string Telefono { get; set; }
        public string Depto { get; set; }
    }
}
