//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fletero_pagos
    {
        public int Fletero_pagos_ID { get; set; }
        public int Fletero_ID { get; set; }
        public System.DateTime Fecha_registro { get; set; }
        public System.DateTime Fecha_pago { get; set; }
        public int Forma_de_pago_ID { get; set; }
        public decimal Monto { get; set; }
        public decimal Importe_viaje { get; set; }
        public string Comentarios { get; set; }
        public int Viaje_ID { get; set; }
        public Nullable<bool> isFicticio { get; set; }
    }
}
