//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles_usuario
    {
        public int Roles_usuario_ID { get; set; }
        public string Nombre { get; set; }
        public int Nivel { get; set; }
        public string Comentarios { get; set; }
    }
}
