//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int Usuario_ID { get; set; }
        public string Usuario1 { get; set; }
        public string Clave { get; set; }
        public int Rol_usuario_ID { get; set; }
        public bool EsAdmin { get; set; }
    }
}
